export type SlugOptions = {
  lowercase?: boolean
  trimHyphens?: boolean
  maxLength?: number
}

export function generateSlug(text: string, options: SlugOptions = {}): string {
  const { lowercase = true, trimHyphens = true, maxLength } = options

  if (!text || typeof text !== "string") return ""

  let slug = text

  slug = slug.normalize("NFD").replace(/[\u0300-\u036f]/g, "")

  slug = slug.replace(/[ঀ-৿]|[^\u0000-\u007F]+/g, (char) => {
    const banglaMap: Record<string, string> = {
      "অ": "a", "আ": "a", "া": "a",
      "ই": "i", "ি": "i",
      "উ": "u", "ূ": "u",
      "এ": "e", "ে": "e",
      "ঐ": "oi", "ৈ": "oi",
      "ও": "o", "ো": "o",
      "ঔ": "ou", "ৌ": "ou",
      "ক": "k", "খ": "kh", "গ": "g", "ঘ": "gh", "ঙ": "ng",
      "চ": "ch", "ছ": "chh", "জ": "j", "ঝ": "jh", "ঞ": "n",
      "ট": "t", "ঠ": "th", "ড": "d", "ঢ": "dh", "ণ": "n",
      "ত": "t", "থ": "th", "দ": "d", "ধ": "dh", "ন": "n",
      "প": "p", "ফ": "ph", "ব": "b", "ভ": "bh", "ম": "m",
      "য": "j", "র": "r", "ল": "l", "শ": "sh", "ষ": "ss", "স": "s", "হ": "h",
      "ড়": "r", "ঢ়": "rh", "য়": "y",
      "ৎ": "t",
      "ং": "ng", "ঃ": "", "ঁ": "n",
      "্": "", "০": "0", "১": "1", "২": "2", "৩": "3", "৪": "4",
      "৫": "5", "৬": "6", "৭": "7", "৮": "8", "৯": "9",
    }
    if (banglaMap[char]) return banglaMap[char]
    return char
  })

  slug = slug.replace(/[^a-zA-Z0-9\s\-_]/g, "")

  slug = slug.replace(/[\s_]+/g, "-")

  if (trimHyphens) {
    slug = slug.replace(/-+/g, "-")
    slug = slug.replace(/^-+|-+$/g, "")
  }

  if (lowercase) {
    slug = slug.toLowerCase()
  }

  if (maxLength && slug.length > maxLength) {
    slug = slug.substring(0, maxLength)
    slug = slug.replace(/-+$/g, "")
  }

  return slug
}

export async function ensureUniqueSlug(
  baseSlug: string,
  checker: (slug: string) => Promise<boolean>,
  options: { maxAttempts?: number; suffix?: string } = {}
): Promise<string> {
  const { maxAttempts = 10, suffix = "-1" } = options

  if (!baseSlug) return ""

  let slug = baseSlug
  let attempt = 1

  while (attempt <= maxAttempts) {
    const exists = await checker(slug)
    if (!exists) return slug

    attempt++
    slug = `${baseSlug}${suffix}${attempt > 2 ? attempt - 1 : ""}`
  }

  return `${baseSlug}-${Date.now()}`
}

export function isSlugManuallyEdited(slug: string, originalName: string): boolean {
  if (!slug || !originalName) return false
  const autoGenerated = generateSlug(originalName)
  return slug !== autoGenerated
}

export function slugifyName(name: string): string {
  return generateSlug(name, { lowercase: true, trimHyphens: true })
}